export const results = [
  {
    name: 'Carrots',
    category: ['vegetable'], 
    isLocal: false,
    isMeat: false,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }, {
    name: '',
    category: [], 
    isLocal: false,
    isMeat: true,
    isProcessed: true,
    isFrozen: true,
    isPlasticPackaged: false
  }
];